"""Publish self-contained, plotted descriptive evidence; no prediction change."""
import json
import hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
data=json.loads((ROOT/'results/data-foundation/layer-workload-analysis-r1/data.json').read_text())
html='''<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>逐层工作量如何改变专家耗时</title>
<style>body{font:16px system-ui;background:#f2f5f9;color:#18283c;margin:0}main{max-width:1150px;margin:auto;padding:24px}section{background:white;border-radius:14px;padding:22px;margin:20px 0}h1{font-size:30px}h2{font-size:21px}p{line-height:1.7}.lead{border-left:5px solid #007b83}select{padding:9px;margin:6px}svg{width:100%;height:auto;min-height:180px}text{font:12px system-ui;fill:#566476}.legend{display:flex;gap:20px;flex-wrap:wrap}.muted{color:#596d81;font-size:14px}a{color:#087f86}table{border-collapse:collapse;width:100%;font-size:14px}td,th{text-align:left;padding:8px;border-bottom:1px solid #ddd}.scroll{overflow:auto}</style>
<main><a href="../prediction-overview-r2/#b-evidence">← 返回1F1B误差分析</a><h1>结构相同，专家实际工作量为什么不同？</h1>
<section class="lead"><h2>把“层位置 → 工作量 → 耗时”接起来</h2><p>同样的hidden size并不保证相同耗时。trace显示路由先选top6，再执行每专家615条的容量筛选。不同层路由结果经过容量处理后，进入专家FC的行数和非空专家数不同，计算量随之改变。</p><p>下面分开看代表rank与完整EP8：前者能比较跨iter，后者能判断是否只是卡间负载转移。这里只解释实测曲线，不修改原预测，不把目标实测当作外推输入。</p></section>
<section><h2>① 逐层曲线：三个iter分别画，不取stage均值</h2><label>规模 <select id="world"><option>256</option><option>224</option></select></label><label>microbatch <select id="mb"></select></label><label>成本阶段 <select id="phase"><option value="B">B专家FC合计</option><option value="recompute">前向重计算FC</option><option value="backward">真实反向FC</option><option value="F">原前向FC</option></select></label><div class="legend"><span style="color:#00877a">● iter40</span><span style="color:#ad4b20">● iter60</span><span style="color:#6557a0">● iter80</span></div><p class="muted">每stage的lane0代表rank。横轴是恢复后的逻辑层号；B执行顺序已经翻转还原。悬停圆点查看精确值。</p><h3>进入专家的行数</h3><div id="work"></div><h3>对应专家FC的GPU GEMM时间（ms）</h3><div id="cost"></div><h3>非空本地专家数量（每rank共20个）</h3><div id="active"></div><div id="stats"></div></section>
<section><h2>② 完整EP8：总量变化，还是卡间搬移？</h2><p>仅256卡iter60，每stage第一组EP8，microbatch跟随上方选择。总量是8卡处理行数相加；最大rank成本只是局部负载指标，不等于层的DAG完成时间。</p><h3>EP8总专家输入行数</h3><div id="total"></div><h3>EP8最忙rank的B专家FC时间（ms）</h3><div id="maxcost"></div><h3>8个rank工作量的CV（标准差÷均值）</h3><div id="cv"></div><p class="muted">完整EP8尚未覆盖iter40/80和另一EDP副本，因此不声称组级跨iter稳定。</p></section>
<section><h2>③ 容量筛选证据与边界</h2><p>224/256共6份代表trace、84个层×microbatch窗口，都可找到：输入[8192,160]上的top6 → 专家轴top615 → logical_and。参考236B源码按容量因子2计算：ceil(8192×6÷160×2)=615；汇集8个发送rank后单专家上限为4920。</p><p>这是容量处理与实测行数变化的一致证据，不是“越深必然越快”的理论，也尚未重建容量处理前的完整路由概率。日志中的旧字段moe_token_dropping=False不能单独证明未裁剪；参考router以capacity_factor是否为空决定是否进入处理。</p><p>B的专家成本=重计算FC1/FC2 + 真实反向FC1/FC2。本页未把门控、token重排、EP通信或未关联空隙归为FC计算，也不把CPU包络差额叫作等待。</p><p id="validation"></p><p><a href="analysis.md">方法、数据与复现说明</a> · <a href="manifest.json">证据清单</a></p></section></main>
<script>const D=__DATA__;const colors=['#00877a','#ad4b20','#6557a0'];
function chart(id,series){let all=series.flatMap(s=>s.values),mx=Math.max(...all.map(x=>x.y),1)*1.08,xlo=Math.min(...all.map(x=>x.x)),xhi=Math.max(...all.map(x=>x.x));const X=x=>64+(x-xlo)/(xhi-xlo||1)*980,Y=y=>235-y/mx*200;let s='<svg viewBox="0 0 1100 280" role="img" aria-label="'+id+'">';for(let i=0;i<=4;i++){let y=mx*i/4;s+=`<path d="M64 ${Y(y)}H1044" stroke="#e2e8ef"/><text x="4" y="${Y(y)+4}">${y>=100?Math.round(y):y.toFixed(2)}</text>`}for(let x=xlo;x<=xhi;x+=4)s+=`<text x="${X(x)}" y="262">L${x}</text>`;series.forEach((a,i)=>{s+=`<polyline fill="none" stroke="${colors[i]}" stroke-width="2" points="${a.values.map(p=>X(p.x)+','+Y(p.y)).join(' ')}"/>`;for(const p of a.values)s+=`<circle cx="${X(p.x)}" cy="${Y(p.y)}" r="3.2" fill="${colors[i]}"><title>${a.label} L${p.x}: ${p.y.toFixed(3)}${p.tip||''}</title></circle>`});document.getElementById(id).innerHTML=s+'</svg>'}
function draw(){let w=+world.value,m=+mb.value,p=phase.value,rs=D.representative.filter(r=>r.world===w&&r.mb===m);for(const [id,key]of [['work','token_rows'],['cost',p+'_FC_gemm_ms'],['active','nonempty_experts']])chart(id,[40,60,80].map(i=>({label:'iter'+i,values:rs.filter(r=>r.iteration===i).sort((a,b)=>a.layer-b.layer).map(r=>({x:r.layer,y:r[key],tip:' PP'+r.stage+' rank'+r.rank}))})));let e=D.ep8.filter(r=>r.mb===m);for(const[id,key]of[['total','total_rows'],['maxcost','max_B_FC_gemm_ms'],['cv','cv']])chart(id,[{label:'256 iter60',values:e.map(r=>({x:r.layer,y:r[key]}))}]);stats.innerHTML='<p class="muted">跨iter逐层形状相关系数（相同microbatch；描述性，不代表因果或预测精度）：</p><table><tr><th>iter对</th><th>工作量</th><th>B FC成本</th></tr>'+D.stability.filter(r=>r.world===w&&r.mb===m).map(r=>`<tr><td>${r.a} / ${r.b}</td><td>${r.workload_r.toFixed(3)}</td><td>${r.cost_r.toFixed(3)}</td></tr>`).join('')+'</table>'}
function reset(){mb.innerHTML=Array.from({length:world.value==='256'?4:3},(_,i)=>'<option>'+i+'</option>').join('');draw()}world.onchange=reset;mb.onchange=phase.onchange=draw;validation.textContent='提取176份trace、2672个层×microbatch×rank记录；与旧B FC成本逐项核对 '+D.regression_checks+' 项通过。';reset();</script></html>'''.replace('__DATA__',json.dumps(data,separators=(',',':')))
html=html.replace('进入专家FC的行数和非空专家数不同','专家实际接收的token条目数和参与计算的专家数量不同')
html=html.replace('<h3>进入专家的行数</h3>','<h3>专家接收token条目数（本rank）</h3><p class="muted">汇总本卡20个专家实际收到的输入。同一个token发给多个专家会计为多条，不是去重后的原始token数。</p>')
html=html.replace('<h3>非空本地专家数量（每rank共20个）</h3>','<h3>本次实际参与计算的本地专家数量（共20个）</h3><p class="muted">实际收到至少1条token输入的专家数量；收到0条的专家仍有权重，只是这次没有输入。</p>')
html=html.replace('<h3>对应专家FC的GPU GEMM时间（ms）</h3>','<h3>对应专家FC的GPU GEMM时间（ms）</h3><p class="muted">与上一图同一rank、同一层的专家线性计算耗时。默认B包含前向重计算与真实反向的FC1/FC2，不是整个B耗时，也不包含全部通信、门控和重排。</p>')
html=html.replace('总量是8卡处理行数相加','总量是8卡专家实际接收的token条目数相加')
html=html.replace('<h3>EP8总专家输入行数</h3>','<h3>EP8专家接收token条目总数（8卡合计）</h3><p class="muted">这张图排除“仅lane0分得少、其余卡分得多”的解释。容量筛选前后要区分：筛选操作已确认，但尚未逐层统计筛选前的分配，因此不能断言曲线下降全部由裁剪增加造成。图中也有回升，不是越深必然越少。</p><p class="muted">“热门专家”指某一层内被更多token选中的专家，不是模型头部层的专家。各层分别路由和筛选；本层被丢弃的专家分配不等于原始token从后续层消失。</p>')
html=html.replace('与实测行数变化','与实测token条目数变化')
capacity_explanation='''<p><strong>固定样本：256卡iter60、MB0，比较中间层L3与L58。</strong>以下结论来自两个完整EP8组的日志与trace核对。</p><h3>实际收到token的专家明显减少</h3><p>每组配置始终为160个专家；组A和组B实际收到至少1条token输入的专家，均由<strong>59个减少到29个</strong>。专家仍然存在，减少的是本次有输入、实际参与工作的专家数量。</p><h3>整个stage的实际专家工作量同时减少</h3><p>两组专家实际接收的token条目合计由<strong>304,032条减少到179,904条，降幅40.83%</strong>。两个组各自都减少，因此不是只观察一个EDP副本造成的现象。</p><h3>发送、接收与计算输入一致</h3><p>两个EP8组、56个中间层、4个microbatch共<strong>71,680项逐专家发送—接收计数核对通过</strong>；接收日志与FC输入也一致。差额在发送计数形成之前已经出现，没有发现收发途中或进入FC时的条目缺失。</p><h3>容量筛选操作得到代码与trace支持</h3><p>已确认top6之后存在专家容量筛选。参考代码及抽查trace的顺序一致：<strong>容量筛选 → 淘汰分配置零 → DeepEP将零概率索引置−1、不发送</strong>。后一步执行淘汰结果，不能重复算作另一次独立丢弃。</p><p class="muted"><strong>结论边界：</strong>59→29和40.83%是该样本筛选后的端点结果，不证明每个相邻层单调下降或跨iter稳定；未取得筛选前逐专家分布和概率，尚不能量化容量超限对全部差额的独立贡献。</p><p><a href="route-filter-origin.md">方法与证据说明</a> · <a href="route-filter-origin-report.json">核对结果</a> · <a href="route-filter-origin-manifest.json">来源与SHA256</a></p>'''
capacity_start=html.index('<section><h2>③ 容量筛选证据与边界</h2>')
capacity_end=html.index('</section>',capacity_start)+len('</section>')
html=html[:capacity_start]+'<section><h2>③ 容量筛选证据与边界</h2>'+capacity_explanation+'<p id="validation" class="muted"></p></section>'+html[capacity_end:]
# Stage boundaries change physical EP8 group. Do not draw misleading cross-stage lines.
html=html.replace('for(let x=xlo;x<=xhi;x+=4)s+=', 'for(let x=xlo;x<=xhi;x+=4){s+=`<text x="${X(x)}" y="18">PP${Math.floor((x-3)/4)+1}</text><path d="M${X(x)-4} 25V235" stroke="#d8e0e8" stroke-dasharray="3 5"/>`}for(let x=xlo;x<=xhi;x+=4)s+=')
html=html.replace('<polyline fill="none" stroke="${colors[i]}" stroke-width="2" points="${a.values.map(p=>X(p.x)+\',\'+Y(p.y)).join(\' \')}"/>', '<path fill="none" stroke="${colors[i]}" stroke-width="2" d="${a.values.map((p,j)=>(j===0||(p.x-3)%4===0?\'M\':\'L\')+X(p.x)+\',\'+Y(p.y)).join(\' \')}"/>')
html=html.replace('横轴是恢复后的逻辑层号；', '横轴是恢复后的逻辑层号，①折线跨PP连续连接；PP标签仍标示物理卡组切换，不代表同一张卡执行所有层；')
# All curves are continuous; PP guides remain, iteration visibility only applies to ①.
html=html.replace("j===0||(p.x-3)%4===0?", "j===0?")
html=html.replace('function chart(id,series){', 'const visibleIterations=new Set([40,60,80]);function chart(id,series){')
html=html.replace('series.forEach((a,i)=>{', "series.forEach((a,i)=>{if(['work','cost','active'].includes(id)&&!visibleIterations.has(Number(a.label.replace('iter',''))))return;")
html=html.replace("document.getElementById(id).innerHTML=s+'</svg>'", "if(['work','cost','active'].includes(id)&&visibleIterations.size===0)s+='<text x=\"400\" y=\"130\">请选择至少一个iter显示曲线</text>';document.getElementById(id).innerHTML=s+'</svg>'")
for iteration,color in [(40,'#00877a'),(60,'#ad4b20'),(80,'#6557a0')]:
    html=html.replace(f'<span style="color:{color}">● iter{iteration}</span>',f'<button type="button" data-iteration="{iteration}" aria-pressed="true" style="color:{color}">● iter{iteration}</button>')
html=html.replace('</style>', 'button[data-iteration]{font:inherit;padding:7px 14px;border:2px solid currentColor;border-radius:8px;background:white;cursor:pointer}button[data-iteration][aria-pressed="false"]{opacity:.45;text-decoration:line-through;border-style:dashed}button[data-iteration]:focus-visible{outline:3px solid #15263d;outline-offset:3px}</style>')
html=html.replace('每stage的lane0代表rank。', '点击iter按钮可显示／隐藏对应曲线，三个图同步切换，纵轴范围不随开关改变。每stage的lane0代表rank。')
toggle_script='''<script>document.querySelectorAll('button[data-iteration]').forEach(button=>button.addEventListener('click',()=>{const iteration=Number(button.dataset.iteration);if(visibleIterations.has(iteration))visibleIterations.delete(iteration);else visibleIterations.add(iteration);button.setAttribute('aria-pressed',String(visibleIterations.has(iteration)));draw();if(typeof pairDraw==='function')pairDraw();}));</script>'''
html=html.replace('</html>',toggle_script+'</html>')
filter_path=ROOT/'results/data-foundation/layer-filtering-r1/report.json'
if filter_path.exists():
    filtering=json.loads(filter_path.read_text())
    section='''<section id="filtering"><h2>④ 新核对：原始分配与实际进入计算的差额</h2><p>256卡iter60、各中间stage第一组EP8。绿色是按trace输入8192×top6×8推导的原始分配393216条；橙色是DeepEP发送计数、接收计数与专家FC输入一致的实测保留量。不是去重token数。</p><div class="legend"><span style="color:#00877a">● 原始top6分配（推导）</span><span style="color:#ad4b20">● 实际进入专家（实测）</span></div><div id="filtercurve"></div><div id="filtercomparison"></div><p>差额是“未进入专家计算的分配量”，不是直接记录的容量丢弃量。已确认容量筛选；参考DeepEP还会屏蔽概率为0的条目。缺少筛选前逐专家分布和概率，不能拆分二者各占多少，更不能把数量恒等式当作容量原因的100%因果证明。</p><p>每层重新路由；不是前一层丢掉原始token、后面层越走越少。曲线有回升，首末层对比不代表单调趋势。本轮不修改预测模型。</p><p><a href="filtering.md">逐层核对方法和边界</a> · <a href="filtering-report.json">计数结果</a> · <a href="filtering-manifest.json">来源与SHA256</a></p></section>'''
    html=html.replace('</main>',section+'</main>')
    js='''<script>const FILTER=__FILTER__;function filteringDraw(){let rs=FILTER.rows.filter(r=>r.mb===+mb.value);chart('filtercurve',[{label:'原始分配（推导）',values:rs.map(r=>({x:r.layer,y:r.offered_assignments}))},{label:'实际接收（实测）',values:rs.map(r=>({x:r.layer,y:r.retained_assignments,tip:' rank'+r.ranks[0]+'～'+r.ranks[7]}))}]);let first=rs[0],last=rs[rs.length-1];document.getElementById('filtercomparison').innerHTML='<p>当前MB'+mb.value+'：L'+first.layer+'实际接收'+first.retained_assignments.toLocaleString()+'条 → L'+last.layer+'实际接收'+last.retained_assignments.toLocaleString()+'条，减少'+(first.retained_assignments-last.retained_assignments).toLocaleString()+'条；原始分配不变。相应未进入计算的差额从'+first.inferred_removed_assignments.toLocaleString()+'增至'+last.inferred_removed_assignments.toLocaleString()+'条。此为数量核对，不是容量丢弃的直接测量。</p>'}mb.addEventListener('change',filteringDraw);world.addEventListener('change',filteringDraw);filteringDraw();</script>'''.replace('__FILTER__',json.dumps(filtering,separators=(',',':')))
    html=html.replace('</html>',js+'</html>')
dest=ROOT/'results/data-foundation/2111-blocks-ui-r1/df-v001/layer-workload-r1'
dest.mkdir(exist_ok=True)
(dest/'index.html').write_text(html)
for source,name in [(ROOT/'docs/data-foundation/ROUTE_FILTER_ORIGIN_R1.md','route-filter-origin.md'),(ROOT/'results/data-foundation/route-filter-origin-r1/report.json','route-filter-origin-report.json'),(ROOT/'results/data-foundation/route-filter-origin-r1/manifest.json','route-filter-origin-manifest.json')]:
    (dest/name).write_bytes(source.read_bytes())
manifest=dest/'manifest.json'
if manifest.exists():
    record=json.loads(manifest.read_text())
    for p in (dest/'index.html',Path(__file__).resolve(),dest/'route-filter-origin.md',dest/'route-filter-origin-report.json',dest/'route-filter-origin-manifest.json'):
        record.setdefault('evidence',{})[str(p)]=hashlib.sha256(p.read_bytes()).hexdigest()
    record['ui_revision']='r3: stage-separated curves and assignment conservation evidence; frozen prediction unchanged. Browser report in original evidence belongs to r1.'
    manifest.write_text(json.dumps(record,indent=2)+'\n')
print(dest)
