import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];BASE=ROOT/'results/data-foundation';src=BASE/'b-cost-blocks-r1';out=BASE/'2111-blocks-ui-r1/df-v001/b-cost-blocks-r1';out.mkdir(exist_ok=False)
D={k:json.loads((src/(k+'.json')).read_text()) for k in ['graph','replay','cost-bindings','summary']}
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>B侧成本块</title><style>*{box-sizing:border-box}body{background:#f3f6fa;color:#24344a;font:16px/1.6 sans-serif;margin:0}main{max-width:1450px;margin:auto;padding:24px}section{background:white;padding:18px;border:1px solid #ccd5df;margin:18px 0}.warn{background:#fff1d9;padding:14px}.scroll{overflow:auto}table{width:100%;border-collapse:collapse}td,th{padding:7px;border-bottom:1px solid #ddd;text-align:left}input{width:120px}select,input,button{font:inherit;padding:6px}a{color:#315d98}</style><main><h1>B侧成本块：重计算与反向分别登记</h1><a href="../cp-ep8-structure-r1/">返回F模型</a> · <a href="graph.json">B图</a> · <a href="cost-bindings.json">参数合同</a><p class="warn">当前是32卡 iter60 PP1 B0的同设备流成本接口。跨流、跨卡CP/EP就绪依赖尚未闭合，不能将此处改成本后的时间视为完整B预测精度，也尚未替换1F1B中的旧B整块。</p><p>每卡四个执行单元，每单元4次重计算CP＋5次反向CP。FusedCombineBackward实际调用Dispatch，FusedDispatchBackward实际调用Combine。外部值替换有效成本，不加在旧B整块上。</p><section><label>rank <select id="rank"></select></label> <label>执行单元 <select id="unit"><option value="0">单元0</option><option value="1">单元1</option><option value="2">单元2</option><option value="3">单元3</option><option value="all">完整B</option></select></label> <label>阶段 <select id="phase"><option value="all">重计算＋反向</option><option value="recompute">重计算</option><option value="backward">反向</option></select></label><button id="reset">恢复trace默认</button><p id="result"></p><p id="error" role="alert"></p><div class="scroll"><table><thead><tr><th>成本块ID</th><th>阶段/类型</th><th>stream</th><th>成本ms</th><th>输入权限</th></tr></thead><tbody id="rows"></tbody></table></div><p>同流连续同类事件合为包络块，不要求逐kernel调参。每块间trace就绪时间另行保留；多个流并行时不能将所有成本相加。单元编号是checkpoint执行顺序，不保证等于正向层编号。</p></section></main><script>
const D=__DATA__,cost={};for(let i=8;i<16;i++){const o=document.createElement('option');o.value=i;o.textContent=i;document.getElementById('rank').append(o)}
function run(){let t={},pending=Object.keys(D.graph);while(pending.length){let ready=pending.filter(k=>D.graph[k].deps.every(d=>d in t));if(!ready.length)throw Error('cycle');for(const k of ready){let n=D.graph[k];t[k]=Math.max(0,...n.deps.map(d=>t[d]))+(cost[k]??n.cost_ms)}pending=pending.filter(k=>!ready.includes(k))}document.getElementById('result').textContent='同流条件回放窗口 '+t.END.toFixed(3)+' ms（不等于完整跨流预测）';return t.END}
function render(){const r=+document.getElementById('rank').value,u=document.getElementById('unit').value,p=document.getElementById('phase').value,b=document.getElementById('rows');b.replaceChildren();let cp=0;for(const[k,n]of Object.entries(D.graph)){if(n.rank!==r||n.kind==='trace_ready'||(u!=='all'&&n.unit!==+u)||(p!=='all'&&n.phase!==p))continue;if(n.kind.startsWith('CP_'))cp++;const tr=document.createElement('tr');for(const v of [k,n.phase+' / '+n.kind,n.stream]){const td=document.createElement('td');td.textContent=v;tr.append(td)}const td=document.createElement('td'),input=document.createElement('input');input.type='number';input.min=0;input.step=.01;input.value=cost[k]??n.cost_ms;input.disabled=D['cost-bindings'][k].policy==='trace_reserved';input.dataset.node=k;input.onchange=()=>{const v=Number(input.value);if(!input.value||!Number.isFinite(v)||v<0){document.getElementById('error').textContent='请输入非负有限成本';return}document.getElementById('error').textContent='';cost[k]=v;run()};td.append(input);tr.append(td);const policy=document.createElement('td');policy.textContent=input.disabled?'trace保留':'有效成本替换';tr.append(policy);b.append(tr)}run();document.getElementById('result').textContent+=' · 当前筛选CP实例 '+cp}
for(const id of ['rank','unit','phase'])document.getElementById(id).onchange=render;document.getElementById('reset').onclick=()=>{for(const k in cost)delete cost[k];document.getElementById('error').textContent='';render()};render();</script></html>'''
(out/'index.html').write_text(html.replace('__DATA__',json.dumps(D)))
for n in ['graph.json','cost-bindings.json','summary.json']:(out/n).write_bytes((src/n).read_bytes())
print(out)
