// Display projection only. Every arrow carries a witness path in the unchanged DAG.
const BSVG='http://www.w3.org/2000/svg';window.bDagViews={};let dagSelection=null;
function bs(tag,attrs={},text){const e=document.createElementNS(BSVG,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e}
function dagPick(key){dagSelection=key;const n=G[key];$('dag-title').textContent=key;$('dag-info').textContent=`当前节点 ${n.cost_ms.toFixed(6)} ms；开始 ${current[key].start_ms.toFixed(3)}，完成 ${current[key].end_ms.toFixed(3)} ms。${n.basis||n.policy||''}`;$('dag-deps').textContent='直接前驱：'+n.deps.join('，');$('dag-cost').value=n.cost_ms;const open=n.policy?.startsWith('external');$('dag-cost').disabled=!open;$('dag-apply').disabled=!open;$('dag-policy').textContent=open?'可替换有效成本；点击应用后整张DAG重算。':'trace保留/边界节点，仅查看；显示的零成本不是整段耗时为零。';}
function projectedEdges(nodes,prefix){const visible=new Set(nodes.map(n=>n.key)),edges=[];for(const n of nodes){const stack=G[n.key].deps.map(k=>[k,[n.key,k]]),seen=new Set();while(stack.length){const [k,path]=stack.pop();if(seen.has(k))continue;seen.add(k);if(visible.has(k)){edges.push({from:k,to:n.key,path:[...path].reverse()});continue}if(prefix&&!k.startsWith(prefix))continue;for(const d of G[k].deps)stack.push([d,[...path,d]])}}return edges}
function isSolid(e){const sig=k=>k.match(/^(U\d+:moe:r\d+:s\d+):/ )?.[1];const s=sig(e.from);return !!s&&s===sig(e.to)&&!e.path.some(k=>/conditional|proxy/i.test(G[k].basis||''))}
function makeDiagram(id,nodes,width,height,prefix,overview=false){const svg=$(id);svg.replaceChildren();svg.setAttribute('viewBox',`0 0 ${width} ${height}`);const defs=bs('defs'),mark=bs('marker',{id:id+'-arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:6,markerHeight:6,orient:'auto'});mark.append(bs('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'#71849b'}));defs.append(mark);svg.append(defs);
 if(!overview)for(let r=8;r<16;r++){const y=62+(r-8)*100;svg.append(bs('rect',{x:0,y:y-12,width,height:96,fill:r%2?'#f3f6fa':'#ffffff'}));svg.append(bs('text',{x:10,y:y+27,'font-size':14,fill:'#425772'},'rank '+r))}
 const map=new Map(nodes.map(n=>[n.key,n]));let edges=projectedEdges(nodes,prefix);if(overview)edges=edges.filter(e=>nodes.findIndex(n=>n.key===e.to)===nodes.findIndex(n=>n.key===e.from)+1);
 for(const e of edges){const a=map.get(e.from),b=map.get(e.to),x1=a.x+a.w,y1=a.y+27,x2=b.x,y2=b.y+27;let d;if(x2>x1)d=`M${x1},${y1} C${(x1+x2)/2},${y1} ${(x1+x2)/2},${y2} ${x2},${y2}`;else d=`M${a.x+a.w/2},${a.y+56} L${a.x+a.w/2},${b.y-13} L${b.x+b.w/2},${b.y-13} L${b.x+b.w/2},${b.y}`;
  const p=bs('path',{d,fill:'none',stroke:'#71849b','stroke-width':1.5,'stroke-dasharray':isSolid(e)?'none':'5 4','marker-end':`url(#${id}-arrow)`,'data-from':e.from,'data-to':e.to});p.append(bs('title',{},`${isSolid(e)?'同流顺序':'折叠或条件依赖'}；路径含${e.path.length}个节点。点击查看路径。`));p.addEventListener('click',()=>{$('dag-title').textContent='连接依据';$('dag-info').textContent='此箭头来自当前DAG路径；隐藏的处理/就绪成本没有删除。';$('dag-deps').textContent=e.path.join(' → ');$('dag-apply').disabled=true});svg.append(p)}
 for(const n of nodes){const group=bs('g',{class:'dag-node',tabindex:0,role:'button','aria-label':n.title,'data-node':n.key});group.append(bs('rect',{x:n.x,y:n.y,width:n.w,height:56,rx:4,fill:n.type==='comm'?'#f2eafa':n.type==='compute'?'#e6effb':'#eef0f3',stroke:n.type==='comm'?'#9471ad':'#96abc4','stroke-width':1.4}));group.append(bs('text',{x:n.x+8,y:n.y+20,'font-size':13,fill:'#24344a'},n.title));const time=current[n.key];group.append(bs('text',{x:n.x+8,y:n.y+41,'font-size':12,fill:'#526981'},n.boundary?`完成 ${time.end_ms.toFixed(2)} ms`:`成本 ${G[n.key].cost_ms.toFixed(3)} ms`));group.append(bs('title',{},`${n.key}\n${time.start_ms.toFixed(3)} → ${time.end_ms.toFixed(3)} ms`));const click=()=>{if(overview){unit=n.unit;selected=null;render()}dagPick(n.key)};group.addEventListener('click',click);group.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();click()}});svg.append(group)}window.bDagViews[id]={nodes,edges};}
function renderBDag(){if(!$('b-overview'))return;const ov=[];for(let u=0;u<4;u++){ov.push({key:`r${rank}:u${u}:recompute`,x:20+u*290,y:28,w:245,title:`第${4-u}层 · 前向重计算`,type:'reserved',unit:u});ov.push({key:`r${rank}:u${u}:backward`,x:20+u*290,y:134,w:245,title:`第${4-u}层 · 真正反向出口`,type:'compute',unit:u,boundary:true})}makeDiagram('b-overview',ov,1180,215,null,true);
 const prefix=`U${unit}:`,entries=Object.entries(G).filter(([k])=>k.startsWith(prefix));const pick=(r,kind)=>entries.find(([k,n])=>n.rank===r&&n.kind===kind)?.[0];const node=(key,x,y,title,type='reserved',w=142,boundary=false)=>{if(!key||!G[key])throw Error('Missing DAG display anchor '+title);return {key,x,y,w,title,type,boundary}};
 const moe=[];for(let r=8;r<16;r++){const y=62+(r-8)*100;const cs=entries.filter(([k,n])=>n.rank===r&&n.kind==='backward_combine_visible');const dispatch=pick(r,'backward_dispatch_visible'),stream=dispatch.match(/:s\d+:/)[0];const output=cs.find(([k])=>k.includes(stream))[0],prep=cs.find(([k])=>!k.includes(stream))[0],p=r-r%2;moe.push(node(dispatch,80,y,'Dispatch 可见部分'),node(pick(r,'expert_grouped_linear_backward_0'),250,y,'FC2 输出投影反向','compute'),node(pick(r,'expert_grouped_linear_backward_1'),420,y,'FC1 输入投影反向','compute'),node(prep,590,y,'本地准备出口','reserved',142,true),node(output,950,y,'Combine 可见尾部'),node(`${prefix}p${p}-${p+1}:u${unit}:r${r}:origin`,1120,y,'梯度处理出口','reserved',142,true))}
 moe.push(node(`${prefix}EP8:combine_effective_completion_gate`,775,412,'Combine跨卡耦合','comm',145));makeDiagram('b-moe-dag',moe,1280,870,prefix);
 const att=[];for(let r=8;r<16;r++){const p=r-r%2,root=`${prefix}p${p}-${p+1}:u${unit}:`,y=62+(r-8)*100;att.push(node(root+`r${r}:origin`,80,y,'Attention 入口','reserved',130,true),node(pick(r,'attention_backward'),730,y,'Attention 反向','compute',142));const reorder=entries.find(([k,n])=>n.rank===r&&n.kind==='index_select_reorder'&&k.includes(':s12:'))?.[0];att.push(node(reorder,555,y,'输入重排','reserved',142));att.push(node(`r${r}:u${unit}:backward`,1450,y,'本层 B 出口','reserved',140,true))}
 for(let p=8;p<16;p+=2){const root=`${prefix}p${p}-${p+1}:u${unit}:pair:`,y=112+(p-8)*100;for(let j=0;j<5;j++)att.push(node(root+`CP${j}`,j<2?240+j*155:910+(j-2)*170,y,`CP${j} · ${p}/${p+1}`,'comm',135))}makeDiagram('b-attention-dag',att,1610,870,null);
 if(dagSelection&&G[dagSelection])dagPick(dagSelection);$('dag-layer-caption').textContent=`当前展开第${4-unit}层 · 仅真反向的八卡DAG投影（前置重计算以包络保留；隐藏就绪/本地处理节点，点击箭头可追溯）`;}
$('dag-apply').onclick=()=>{const value=Number($('dag-cost').value);if(!dagSelection||!G[dagSelection].policy?.startsWith('external')||$('dag-cost').value.trim()===''||!Number.isFinite(value)||value<0){$('dag-policy').textContent='请输入非负有限有效成本；保留节点不能修改。';return}G[dagSelection].cost_ms=value;render()};
